version: 0.1.{build}
image:
# - Ubuntu1604
- Visual Studio 2017
install:
- cmd: dir C:\Libraries\boost_1_67_0\lib64-msvc-14.1
- cmd: choco install bazel
- sh: >-
    sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python

    sudo apt-get install openjdk-8-jdk

    sudo add-apt-repository ppa:webupd8team/java

    sudo apt-get update && sudo apt-get install oracle-java8-installer

    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

    sudo apt-get update && sudo apt-get install bazel
- cmd: .\download_and_build_third_party_libs_windows.ps1
- sh: ./download_and_build_third_party_libs.sh
build_script:
- cd src
- bazel build //automaton/...
test_script:
- cd src
- bazel test //automaton/tests/...
