version: 0.1.{build}

image:
- Ubuntu1604
- Visual Studio 2017

only_commits:
  files:
    - appveyor.yml
    - download_and_build*.*
    - src/

for:
-
  matrix:
    only:
      - image: Ubuntu1604
  cache:
  - src/build -> src/CMakeLists.txt
  - src/local_third_party/bitcoin -> download_and_build_third_party_libs.sh
  - src/local_third_party/googletest -> download_and_build_third_party_libs.sh
  - src/local_third_party/cryptopp -> download_and_build_third_party_libs.sh
  - src/local_third_party/LuaJIT -> download_and_build_third_party_libs.sh
  - src/local_third_party/sol2 -> download_and_build_third_party_libs.sh
  - src/local_third_party/g3log -> download_and_build_third_party_libs.sh
  - src/local_third_party/ed25519 -> download_and_build_third_party_libs.sh
  - src/local_third_party/protobuf -> download_and_build_third_party_libs.sh
  - src/local_third_party/lua -> download_and_build_third_party_libs.sh
  - src/local_third_party/JUCE -> download_and_build_third_party_libs.sh
  # - src/local_third_party/bazel-0.21.0-installer-linux-x86_64.sh
  - src/local_third_party/boost_1_70_0.tar.gz
  - src/local_third_party/bzip2-1.0.6.tar.gz
  - src/local_third_party/CRYPTOPP_7_0_0.tar.gz
  - src/local_third_party/easyloggingpp-9.96.7.tar.gz
  - src/local_third_party/g3log-1.3.2.tar.gz
  - src/local_third_party/googletest-release-1.8.1.tar.gz
  - src/local_third_party/JUCE-5.4.3.tar.gz
  - src/local_third_party/lua-5.3.5.tar.gz
  - src/local_third_party/LuaJIT-2.0.5.tar.gz
  - src/local_third_party/replxx-release-0.0.1.tar.gz
  - src/local_third_party/v0.17.1.tar.gz
  - src/local_third_party/v3.6.1.2.tar.gz
  - src/local_third_party/xz-5.2.3.tar.gz
  - src/local_third_party/zlib-1.2.11.tar.gz
-
  matrix:
    only:
      - image: Visual Studio 2017
  cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - src\local_third_party\lua -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\LuaJIT -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\replxx -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\cryptopp -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\ed25519 -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\googletest -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\protobuf -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\g3log -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\JUCE -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\zlib-1.2.11.zip -> download_and_build_third_party_libs_windows.ps1
  - src\local_third_party\*.zip -> download_and_build_third_party_libs_windows.ps1

install:
# - cmd: choco install bazel
# - cmd: Powershell.exe -executionpolicy remotesigned -File .\download_and_build_third_party_libs_windows.ps1
# - cmd: pwd
# - cmd: dir src\local_third_party
# - sh: >-
#     sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
#
#     sudo wget https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-installer-linux-x86_64.sh
#
#     sudo chmod +x bazel-0.21.0-installer-linux-x86_64.sh
#
#     sudo ./bazel-0.21.0-installer-linux-x86_64.sh
- sh: ./download_and_build_third_party_libs.sh
# examine build state
- sh: pwd
- sh: ls -la src/local_third_party
build_script:
- cd src
# - bazel build --incompatible_package_name_is_a_function=false //automaton/...

test_script:
# - cmd: bazel test --test_output=errors --test_size_filters=small --test_tag_filters=-flaky //automaton/tests/...
- sh: cd automaton && ./lint.sh && ./lint_ui.sh && cd ..
- sh: mkdir -p build && cd build
- sh: cmake -DCMAKE_BUILD_TYPE=Release .. && make -j8 && make -j8 test CTEST_OUTPUT_ON_FAILURE=TRUE
- sh: cd ..
# - sh: bazel test --test_output=errors --test_size_filters=small --incompatible_package_name_is_a_function=false //automaton/tests/...
