version: 0.1.{build}

image:
- Ubuntu1604
- Visual Studio 2017

only_commits:
  files:
    - appveyor.yml
    - download_and_build_third_party_libs.*
    - src/

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

for:
-
  matrix:
    only:
      - image: Ubuntu1604
  cache:
  - src/local_third_party/*.gz -> appveyor.yml

install:
- cmd: choco install bazel
- cmd: Powershell.exe -executionpolicy remotesigned -File .\download_and_build_third_party_libs_windows.ps1
- sh: >-
    sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python

    sudo apt-get install openjdk-8-jdk

    sudo add-apt-repository ppa:webupd8team/java

    sudo apt-get update && sudo apt-get install oracle-java8-installer

    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

    sudo apt-get update && sudo apt-get install bazel
- sh: ./download_and_build_third_party_libs.sh

build_script:
- cd src
# - bazel build --incompatible_package_name_is_a_function=false //automaton/...

test_script:
- cmd: bazel test --test_size_filters=small --test_tag_filters=-flaky //automaton/tests/...
- sh: bazel test --test_size_filters=small --incompatible_package_name_is_a_function=false //automaton/tests/...
