name: C/C++ CI

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/ccpp.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/ccpp.yml'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]
    env:
      build_dir: ./src/build
      dist_dir: ./src/local_third_party
      build_deps: OFF
      automaton_version: v0.1.10a
    steps:
    - uses: actions/checkout@v2
    - name: Check for full rebuild
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
           echo "::set-env name=build_deps::ON"
      shell: bash
    - name: Get tag information
      if: startsWith(github.ref, 'refs/tags/v')
      id: tag
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\//, '');
    - name: Install build dependencies
      run: choco install zip
    - name: prepare
      run: |        
        mkdir ${{ env.build_dir }}
        mkdir ${{ env.dist_dir }}
    - name: Fetch dependencies
      if: startsWith(env.build_deps, 'OFF')
      working-directory: ${{ env.dist_dir }}
      run: |
        curl -L -O https://github.com/automaton-network/automaton/releases/download/${{ env.automaton_version }}/automaton-Windows-${{ matrix.configuration }}-${{ matrix.platform }}-${{ env.automaton_version }}.zip
        unzip automaton-Windows-${{ matrix.configuration }}-${{ matrix.platform }}-${{ env.automaton_version }}.zip
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0    
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -A ${{ matrix.platform }} -Dautomaton_STATIC_RUNTIME=OFF -Dautomaton_BUILD_DEPS=${{ env.build_deps }} -DCMAKE_INSTALL_PREFIX=../local_third_party
      shell: cmd
    - name: build
      working-directory: ${{ env.build_dir }}
      run: msbuild /t:Build INSTALL.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
      shell: cmd
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
      shell: cmd
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.dist_dir }}
      run: zip -r ../../automaton-Windows-${{ matrix.configuration}}-${{ matrix.platform}}-${{ steps.tag.outputs.result }}.zip .
      shell: cmd
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: automaton-Windows-${{ matrix.configuration }}-${{ matrix.platform}}-${{ steps.tag.outputs.result }}.zip
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
      dist_dir: ./src/local_third_party
    steps:
    - uses: actions/checkout@v2
    - name: Get tag information
      if: startsWith(github.ref, 'refs/tags/v')
      id: tag
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\//, '');
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.dist_dir }}
      run: zip -r ../../automaton-Linux-${{ matrix.configuration}}-${{ steps.tag.outputs.result }}.zip .
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: automaton-Linux-${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.zip
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
      lint_dir: ./src/automaton
      dist_dir: ./src/local_third_party
      MACOSX_DEPLOYMENT_TARGET: 10.9
    steps:
    - uses: actions/checkout@v2
    - name: Get tag information
      if: startsWith(github.ref, 'refs/tags/v')
      id: tag
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          return context.payload.ref.replace(/refs\/tags\//, '');
    - name: Install build dependencies
      run: brew install autoconf automake libtool
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.dist_dir }}
      run: zip -r ../../automaton-macOS-${{ matrix.configuration}}-${{ steps.tag.outputs.result }}.zip .
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: automaton-macOS-${{ matrix.configuration }}-${{ steps.tag.outputs.result }}.zip
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint checks
        run: ./lint.sh
        working-directory: ./src/automaton
