name: C/C++ CI

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/ccpp.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/ccpp.yml'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [Win32, x64]
    env:
      build_dir: ./src/build
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0    
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -A ${{ matrix.platform }} -Dautomaton_STATIC_RUNTIME=OFF -DCMAKE_INSTALL_PREFIX=../local_third_party
      shell: cmd
    - name: build
      working-directory: ${{ env.build_dir }}
      run: msbuild /t:Build INSTALL.vcxproj /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
      shell: cmd
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
      shell: cmd
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.build_dir }}/local_third_party
      run: zip -r ../../../Windows-${{ matrix.configuration}}-${{ matrix.platform}}-$GITHUB_SHA.zip .
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: Windows-${{ matrix.configuration }}-${{ matrix.platform}}-${{ github.sha }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.build_dir }}/local_third_party
      run: zip -r ../../../Linux-${{ matrix.configuration}}-$GITHUB_SHA.zip .
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: Linux-${{ matrix.configuration }}-${{ github.sha }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      build_dir: ./src/build
      lint_dir: ./src/automaton
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: brew install autoconf automake libtool
    - name: prepare
      run: mkdir ${{ env.build_dir }}
    - name: configure
      working-directory: ${{ env.build_dir }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_INSTALL_PREFIX=../local_third_party
    - name: build
      working-directory: ${{ env.build_dir }}
      run: make install
    - name: test
      working-directory: ${{ env.build_dir }}
      run: ctest -j4 -C ${{ matrix.configuration }}
    - name: Archive
      if: startsWith(github.ref, 'refs/tags/v')
      working-directory: ${{ env.build_dir }}/local_third_party
      run: zip -r ../../../macOS-${{ matrix.configuration}}-$GITHUB_SHA.zip .
    - name: Release      
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: macOS-${{ matrix.configuration }}-${{ github.sha }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint checks
        run: ./lint.sh
        working-directory: ./src/automaton
